### ISSUE TITLE
bug: gh-dash module broken after #6582

### ISSUE THREAD

**Issue by sedlund** [nix-community/home-manager#6584]
### Are you following the right branch?

- [x] My Nixpkgs and Home Manager versions are in sync

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Issue description

gh-dash fails to build after #6582  reverting to prior commit resolves

```
       … while evaluating the option `programs.gh.extensions':

       … while evaluating definitions from `/nix/store/frd8jxkz2mf4g9c1qqhbl7m8qxhkl6hf-source/modules/programs/gh-dash.nix':

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attempt to call something which is not a function but a Boolean: true
       at /nix/store/frd8jxkz2mf4g9c1qqhbl7m8qxhkl6hf-source/modules/programs/gh-dash.nix:37:30:
           36|
           37|     programs.gh.extensions = (cfg.package != null) [ cfg.package ];
             |                              ^
           38|
🚀 ❌ [deploy] [ERROR] Failed to evaluate deployment data: Evaluation resulted in a bad exit code: Some(1)
```

### Maintainer CC

@khaneliman 

### System information

```markdown
- system: `"x86_64-linux"`
 - host os: `Linux 6.12.13, NixOS, 25.05 (Warbler), 25.05.20250305.d69ab0d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.24.12`
 - nixpkgs: `/nix/store/b19xi89pgm1arig3l9xqn1h81zjd1j91-source`
```
